[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = [
    "SegMintKYCRegistry",
    "SegMintVaultManagerProxy",
    "SegMintVaultManager",
    "SegMintVault"
]

[fmt]
bracket_spacing = true