[profile.default]
src = "src"
out = "out"
evm_version = "paris"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
gas_reports = [
    "VaultFactory",
    "OperatorFilter",
    "TypeHasher",
    "UpgradeHandler",
    "NonceManager",
    "AccessRegsitry",
    "SignerRegistry",
    "KeyExchange",
    "Keys",
    "MAVault",
    "SAVault"
]
fallback_oz = true
is_system = false # Note: NonceHolder and the ContractDeployer system contracts can only be called with a special isSystem flag as true
mode = "3"

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
abstract = "${ABSTRACT_RPC_URL}"

[fmt]
bracket_spacing = true