[profile.default]
src = "src"
out = "out"
evm_version = "paris"
libs = ["lib"]
gas_reports = [
    "SegMintKYCRegistry",
    "SegMintVaultManagerProxy",
    "SegMintVaultManager",
    "SegMintVault",
    "SignerManagerMock"
]

[fmt]
bracket_spacing = true